# Artificial Neural Network

### Importing the libraries

In [31]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [32]:
tf.__version__

'2.4.1'

## Data Preprocessing

### Importing the dataset

In [33]:
df = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [34]:
df.head(3)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1

In [35]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [36]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [38]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [40]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

In [43]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling the ANN

In [44]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [45]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7675 - accuracy: 0.4243
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4984 - accuracy: 0.8034
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4409 - accuracy: 0.8162
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4204 - accuracy: 0.8273
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4238 - accuracy: 0.8223
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4221 - accuracy: 0.8194
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4023 - accuracy: 0.8307
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3964 - accuracy: 0.8318
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3986 - accuracy: 0.8352
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3937 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3495 - accuracy: 0.8562
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3353 - accuracy: 0.8628
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8675
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3433 - accuracy: 0.8610
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3386 - accuracy: 0.8642
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3460 - accuracy: 0.8606
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3302 - accuracy: 0.8692
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3325 - accuracy: 0.8659
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3371 - accuracy: 0.8630
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3424 - accuracy: 

### Predicting the Test set results

In [46]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1506   89]
 [ 184  221]]


0.8635